### ISSUE TITLE
Meta: incorporate key documents/ending steps

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-HousingCodeChecklist#12]
Incorporate at least as a draft the following ending choices a tenant can make:

- [x] Housing code checklist
- [x] Evidence packet
- [x] Repair letter
- ~[ ] Repair and deduct?~
- [x] Inspection request letter (needed? could be checklist + instructions on how to call)
- [x] Petition to enforce sanitary code
- [x] TRO (connect to the CFO TRO form)
- [x] Connect w/ tenant organizer (info page)
- [x] Sue for money damages? (Probably just info page for now)

**Comment by nonprofittechy** [comment]
Remove Withholding rent letter
